controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Comment;
use app\models\CommentForm;
use app\models\CreateFeedbackForm;
use app\models\Feedback;
use app\models\FeedbackImg;
use app\models\RegistrationForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'isGuest' => Yii::$app->user->isGuest,
            'feedbacks' => Feedback::find()->all(),
        ]);
    }

    /**
     * Displays create page.
     *
     * @return string|Response
     */
    public function actionCreate() {

        $feedback = new CreateFeedbackForm();

        if ($feedback->load(Yii::$app->request->post())) {
            $feedback->image = UploadedFile::getInstance($feedback, 'image');
            //$feedback->saveFeedback();
            $feedback->saveImg($feedback->saveFeedback()->id);
            return $this->redirect('index');
        }

        return $this->render('create_feedback', [
            'feedback' => $feedback,
        ]);
    }

    /*public function actionEdit($id) {

        $feedback = Feedback::getFeedback($id);

        if (Yii::$app->request->isPost) {

        }

        return $this->render('edit_feedback', [
            'feedback' => $feedback,
        ]);
    }*/

    /*public function actionUpload($id) {

        $feedbackImg = new FeedbackImgForm();

        $feedbackImg->load(Yii::$app->request->post());
        $feedbackImg->saveImg($id);

        return $this->refresh('create_feedback');
    }*/

    public function actionLike($id) {

        $feedback = Feedback::findOne(['id' => $id]);

        $feedback->likeCount();

        return $this->actionIndex();
    }

    public function actionLikeInShow($id) {
        $feedback = Feedback::findOne(['id' => $id]);

        $feedback->likeCount();
        return $this->actionShowFeedback($id);
    }

    public function actionLikeComment($id) {

        $comment = Comment::findOne(['id' => $id]);
        $comment->like();

        return $this->actionShowFeedback($comment->feedbackId);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Registration action.
     *
     * @return Response|string
     */
    public function actionRegistration() {

        $user = new RegistrationForm();

        if ($user->load(Yii::$app->request->post())) {
            //if ($user->validate()) {
                Yii::$app->user->login($user->signIn()/*, $this->rememberMe ? 3600*24*30 : 0*/);
            //}
            return $this->goBack();
        }

        return $this->render('registration', [
            'user' => $user,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionShowFeedback($id) {
        $feedback = Feedback::getFeedback($id);
        $feedbackImg = FeedbackImg::getAllPathById($id);

        $comment = new CommentForm();
        $comments = Comment::getComments($id);

        if (Yii::$app->request->isPost) {
            $comment->load(Yii::$app->request->post());
            $comment->image = UploadedFile::getInstance($comment, 'image');
            $comment->saveImg($comment->saveComment($id)->id);

            /*return $this->renderAjax('show_feedback', [
                'feedback' => $feedback,
                'comment' => $comment,
                'comments' => $comments,
                'feedbackImg' => $feedbackImg,
            ]);*/
            return $this->refresh('show_feedback');
        }

        return $this->render('show_feedback', [
            'feedback' => $feedback,
            'comment' => $comment,
            'comments' => $comments,
            'feedbackImg' => $feedbackImg,
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }*/

    /**
     * Displays about page.
     *
     * @return string

    public function actionAbout()
    {
        return $this->render('about');
    } */
}

views/site/create_feedback.php
<?php

use app\models\CreateFeedbackForm;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $feedback CreateFeedbackForm*/

$this->title = 'Create Feedback';
?>

<div class="reviews-form">

    <h1><?= Html::encode($this->title) ?></h1>

    <!--<div class="alert alert-success col-lg-12" role="alert">
        <?/*= Yii::$app->session->getFlash('feedback'); */?>
    </div>-->

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($feedback, 'username')->textInput([
        'maxlength' => true,
        'value' => Yii::$app->user->identity->username,
        'readonly' => true,
    ]) ?>

    <?= $form->field($feedback, 'feedback_text')->textarea(['rows' => 10]) ?>

    <?/*= $form->field($model, 'date')->widget(DateControl::classname(), [
        'type' => 'date',
    ]) */?>

    <?/*= $form->field($feedback, 'status_active')->dropDownList([0 => 'неактивный', 1 => 'активный']) */?>

    <?/*= $form->field($model, 'image')->fileInput() */?><!--
    <button>Load</button>-->
    <?= $form->field($feedback, 'image')->fileInput() ?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/edit_feedback.php
<?php

?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $isGuest bool*/
/* @var $feedbacks Feedback*/

use app\models\Feedback;
use app\models\User;
use yii\helpers\Html;

$this->title = 'Guest Book';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Guest Book!</h1>

        <p class="lead">Here you can leave your feedback! Thanks for that!)</p>
    </div>

    <div class="col-8">
        <?php if (!$isGuest): ?>

            <div class="form-group">
                <?= Html::a('Send Feedback', ['/site/create'], ['class'=>'btn btn-primary']) ?>
            </div>
            <?php if (empty($feedbacks)): ?>
                <div class="align-content-center">
                    <p>There are no reviews yet)</p>
                </div>
            <?php else: ?>
                <?php foreach ($feedbacks as $note): ?>
                    <div class="container">
                        <div class="col">
                            <div class="col-lg-1">
                                <h4><?= Html::a(User::findById($note->userId)->username, ['show-feedback', 'id' => Html::encode($note->id)]) ?></h4>
                            </div>
                            <div class="col-lg-12">
                                <?= $note->feedback_text ?>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <?= $note->date ?>
                                </div>
                                <div class="col-lg-7"></div>
                                <div class="col-lg-1">
                                    <?= Html::a($note->like, ['/site/like', 'id' => Html::encode($note->id)])?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>


</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to registration:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="container">
            <div class="row">
                <div class="offset-lg-1 row-1">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
                <div class="offset-1 row-1">
                    <?= Html::a('Registration', ['/site/registration'], ['class'=>'btn btn-primary']) ?>
                </div>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/registration.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $user app\models\User */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Registration';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-registration">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'registration-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label'],
        ],
    ]); ?>

    <?= $form->field($user, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($user, 'password')->passwordInput() ?>

    <?/*= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ]) */?>

    <div class="form-group">
        <div class="offset-lg-1 col-lg-11">
            <?= Html::submitButton('Registration', ['class' => 'btn btn-primary', 'name' => 'registration-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/show_comments.php
<?php

?>

views/site/show_feedback.php
<?php


use app\models\Comment;
use app\models\CommentForm;
use app\models\CommentImg;
use app\models\Feedback;
use app\models\FeedbackImg;
use app\models\User;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $feedback Feedback */
/* @var $comment CommentForm */
/* @var $comments Comment */
/* @var $feedbackImg FeedbackImg*/
/* @var $commentImg CommentImg*/

$this->title = 'Feedback'
?>

<div class="site-feedback">
    <div class="container">
        <?php Pjax::begin() ?>
        <div class="row">
            <div class="col-lg-auto">
                <h3> <?= User::findById($feedback->userId)->username ?> </h3>
            </div>
        </div>
        <div class="row">
            <?= $feedback->feedback_text ?>
        </div>
        <div class="row">
            <div class="col-lg-auto">
                <?= $feedback->date ?>
            </div>
            <div class="col-lg-9"></div>
            <div class="col-lg-auto">
                <?= Html::a($feedback->like, ['/site/like-in-show', 'id' => Html::encode($feedback->id)])?>
            </div>
        </div>
        <div class="row">
            <?php if($feedbackImg->path !== null): ?>
                <img src="<?= $feedbackImg->path?>" alt="">
            <?php endif; ?>
        </div>
        <?php Pjax::begin()?>
        <div class="container">
            <?php Pjax::begin() ?>
            <?php foreach ($comments as $note): ?>
                <div class="container">
                    <div class="row">
                        <?= User::findById($note->userId)->username ?>
                    </div>
                    <div class="row">
                        <?= $note->commentText ?>
                    </div>
                    <div class="row">
                        <?= Html::a($note->like, ['/site/like-comment', 'id' => Html::encode($note->id)])?>
                    </div>
                    <div class="row">
                        <?php $commentImg = CommentImg::getCommentImgById($note->id)?>
                        <?php if($commentImg->path !== null): ?>
                            <img src="<?= $commentImg->path?>" alt="">
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach ?>
            <?php Pjax::end() ?>
        </div>
        <?php if (Yii::$app->user->id == $feedback->userId || Yii::$app->user->id == 3): ?>
            <div class="col-12">
                <?php $form = ActiveForm::begin([
                    'id' => 'form-comment',
                    'layout' => 'horizontal',
                    'fieldConfig' => [
                        'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                        'labelOptions' => ['class' => 'col-lg-1 col-form-label'],
                    ],
                    'options' => ['enctype' => 'multipart/form-data'],
                ])
                ?>

                <?= $form->field($comment, 'username')->textInput([
                    'maxlength' => true,
                    'value' => Yii::$app->user->identity->username,
                    'readonly' => true,
                ]) ?>


                <?= $form->field($comment, 'commentText')->textarea(['rows' => 5]) ?>

                <?= $form->field($comment, 'image')->fileInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Leave a comment', ['class' => 'btn btn-success']) ?>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        <?php endif ?>
    </div>
</div>

<?php
/*$js = <<<JS
        $('.btn').on(function () {
            var data = $(this).serialize();
            $.ajax({
                url: '/site/show-feedback',
                type: 'POST',
                data: {'data': data},
                success: function (res) {
                    alert('Save comment');
                },
                error: function () {
                    alert('Error!');
                }
            });
            return false;
        });
JS;

$this->registerJs($js);*/
?>